[package]
name = "Day18"
version = "0.1.0"
authors = ["Nikolas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.14.0"
pathfinding = "2.0.1"
permutohedron = "0.2.4"
factorial = "0.1.1"