[package]
name = "Day9"
version = "0.1.1"
authors = ["Nikolas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path ="../intcode" }
