[package]
name = "Day25"
version = "0.1.0"
authors = ["nikolas <nikolas.degiorgis>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path ="../intcode" }